unbind C-b
set -g prefix C-Space

# https://ostechnix.com/install-tmux-plugin-manager/
# https://ostechnix.com/save-and-restore-tmux-environment/
# reload: tmux source ~/.tmux.conf
# install: Ctrl+b, I
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum' #Last in list

#Restore tmux state when starting
set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'