#! /usr/bin/env python3
import random

phrases=[
    "As the prophecy foretold.",
    "But at what cost?",
    "So let it be written; so let it be done.",
    "So… it has come to this.",
    "That\'s just what he/she/they would\'ve said.",
    "Is this why fate brought us together?",
    "And thus, I die",
    "…just like in my dream…",
    "Be that as it may, still may it be as it may be",
    "There is no escape from destiny",
    "Wise words by wise men write wise deeds in wise pen.",
    "In this economy?",
    "…and then the wolves came.",
    "Six one way, half a dozen the other.",
    "Fear not! -- ScoOoOoter",
    "Has anyone really been far even as decided to use even go want to do more like?",
    "I\'ve been further even more decided to use even go need to do look as anyone can!",
    "I have no strong feelings one way or the other.",
    "I think there\'s a \"k\" in knucklehead.",
    "I have 4 other goals to accomplish today.",
    "…in the noon. -- ScoOoOoter",
    "I punch those numbers into my calculator, it makes a happy face!",
    "It\'s my first day!",
    "Send in the clergy! They can move diagonally!",
    "Rest assured that all lethal military androids have been provided with one copy of the Laws of Robotics. To share.",
    "To shreds you say?",
    "Super easy! Barely an inconvenience!",
    "All hail Hypnotoad!",
    "Bob Vance - Vance refrigeration",
    "And that\'s the way the cookie crumbles",
    "At no point in your rambling, incoherent response were you even close to anything that could be considered a rational thought",
    "I award you no points and may God have mercy on your soul",
    "It\'s Halloween.... That\'s really good timing!",
    "Ok, lamp time\'s over!",
    "This isn\'t Sesame Street...",
    "My plan is to forget the whole thing and hope for the best.",
    "Please stop screaming into the void. It\'s getting full.",
    "Today is brought to you by the letters \"W\", \"T\", and \"F\"",
    "That sentence ended a lot better than it began",
    "Now with even less asbestos!",
    "Not everyone who wears a sweater is Mr. Rogers.",
    "He doesn\'t know how to use the 3 seashells!",
    "Am I sgeaking a different language?!?",
    "You can\'t steer with a rudder like that",
    "Whatever boats your float",
    "Boaty McBoatface",
    "Never underestimate the cleverness of fools",
    "On today\'s episode of \'Why is this sticky?\'...",
    "A lack of planning on your part does not constitute an emergency on mine.",
    "You are technically correct. The best kind of correct.",
    "0118 999 881 999 119 7253",
    "Quando omni flunks moritati",
    "The early bird gets the worm, but the second rat gets the cheese.",
    "That happens sometimes",
    "...and my middle name is Kurt, not Fart",
    "Never do this to a badger...",
    "KWYJIBO",
    "You\'re paying way too much for worms, man. Who's your worm guy?",
    "I\'m the reason we have rules.",
    "If I can\'t scuba, then what\'s this all been about?",
    "The Enrichment Center reminds you that the Weighted Companion Cube cannot speak.",
    "Well done. Here come the test results: You are a horrible person.",
    "I\'m serious, that\'s what it says: A horrible person. We weren\'t even testing for that.",
    "How the turns have tabled...",
    "So do both of yourselves a favor and just let that handsome devil go about his business.",
    "...that\'s not part of the test. That\'s asbestos.",
    "You\'re not a super cop are you? You\'re just an ordinary idiot.",
    "But for the love of God Patrick, you\'re not a sheep dog!",
    "Do you know how expensive that cheese was? We might as well had built a children\'s hospital!",
    "In this house we obey the laws of thermodynamics!",
    "Why do I get the feeling that someday I\'ll be describing this to a psychiatrist?",
    "Anyway, don\'t stress yourself thinking about it. Visualizing the scenario while under stress actually triggers the reaction.",
    "Go to the Winchester, have a nice cold pint, and wait for all of this to blow over.",
    "Freaking Canada",
    "I found it on the hair dryer!",
    "Me fail English? That\'s unpossible!",
    "Stupid sexy Flanders",
    "Uh....Are you gonna tell her?",
    "Kerfonta University: Home of the Schooler",
    "We do what we must because we can",
    "Luck is a concept invented by the weak to explain their failures.",
    "Apathy\'s a tragedy and boredom is a crime.",
    "I eat all of the cheese",
    "My mush is brian",
    "I can\'t believe you\'ve done this",
    "I like the ones that insults me sometimes better",
    "How \'bout eggs?",
    "It\'s pronounced \'gif\', not \'gif\'.",
    "Today is a day",
    "How long do you think the curb life of cheese is?",
    "I\'m assuming in this case that I am your homeboy -- Shrek",
    "I always thought they were saying, \'There\'s a bathroom on the right...\'",
    "I am not a clever man.",
    "You\'re family tree is more twisted than your DNA.",
    "With an \'a\' it looks like Gary if you\'re an idiot.",
    "These random numbers suck",
    "Milk is the gateway drug to cheese.",
    "My therapist thought this was funny.",
    "Good news! It\'s a repository!",
    "It\'s ok to pray naked",
    "Well, goodbye socks",
    "It doesn\'t take a lot to keep a chicken busy.",
    "Well, that wasn\'t such a chore, now, was it?",
    "I think I saw a 2...",
    "I\'ve created a new 9 bit system..... the 9th bit is always on",
    "correcthorsebatterystaple",
    "I found a banana!",
    "Then who was phone?",
    "I didn\'t wanna **** myself on the internet",
    "49620 -- Nemire",
    "eschew obfuscation",
    f"There\'s always {random.choice(['money','caffeine'])} in the banana stand",
    "Do they speak English in What?",
    "Okay. But dogs CAN look up!",
    "Are you creating a logistic model based off of two points?",
    "Do you have any lent plans?",
    "On no account allow a Vogon to read poetry at you.",
    "What a mystery this is",
    "What\'s the plural of simplex? Simplices. What\'s the plural of complex? Complexen!",
    f"It\'s just a little {random.choice(['dirty','slimey','airborne'])}. It\'s still good! It\'s still good!",
    "My disappointment is immeasurable, and my day is ruined.",
    "I don\'t know man... I just work here.",
    "The... bubbles help.",
     "Angel, you've got a brain the size of a planet. Don't give me \'I dunno.\'",
    "Crazy world. Lotta smells.",
    "These 4 pixels are wrong...",
    f"The {random.choice(['broken AC','condescending emails','floggings','beatings','prelims'])} will continue until morale improves.",
    "I used to be an academic like you... then I took a prelim to the knee.",
    "It\'s better for the insurance if we don\'t know what\'s going on.",
    "Characters add up ya know? Just like period sizes.",
    "Wadsworth’s Constant: You can safely skip the first third of any YouTube video to get to the good part",
    "Poe’s Law: no matter how sarcastic you are on the Internet, somebody will take it seriously",
    "Muphry’s law: if you correct somebody’s grammar or spelling, your correction will it self contain a typo or grammatical error",
    "Goodwin’s law: any arguments on the Internet will inevitably devolve into somebody accusing the other of being a Nazi or Hitler",
    "Armstrong’s law: If you argue with an American, they will inevitably reference the moon landing",
    "Hofstadter’s law: everything takes longer than you think it will even after accounting for Hofstadter’s law",
    "Cunningham’s law: The best way to get an answer on the Internet is to confidently post the wrong answer and let someone correct you",
    "Occam’s razor: The simplest explanation is most likely",
    "Hanlen’s razor: Never attribute to malice that which can be attributed to incompetence",
    "It\'s not a lie if you believe it.",
    "A change in perspective is worth 80 IQ points.",
    "It ain\'t stupid if it works...",
    "1000101",
    "110100100",
    "01101110 01100101 01110010 01100100",
    "Brawndo\'s got what plants crave: It's got electrolytes!",
    "Pacman's an idiot",
    "I'm way too emotionally invested in this",
    "The hamster only ate one egg today",
    "Do you eat peanuts with the shells on?",
    "It was small, quiet, and a waste of my time",
    "Pancakes and brisket is the new chicken and waffles",
    "With enough cheese, you can do anything -- Byrd",
    f"The {random.choice(['French','humans'])} have a saying:",
    "There's something about the name Bill. It's only given to the worthy.",
    "Never accept any wooden nickels.",
    "'Give me a number with several factors....'  '37'",
    "Toots are in my butt",
    "You are like an old television!",
    "I am a benevolent duck lord",
    "Stairs or scramble?",
    "No Fair! You changed the outcome by measuring it!",
    "thoughts create feelings",
    "What is today, but yesterday's tomorrow?",
    "Hello. I am Inigo Montoya. You killed my father. Prepare to die.",
    "I find that answer vague and unconvincing",
    "Quiet! And there's a fresh one if you mouth off again.",
    "Congratulations, you are being rescued.",
    "I'm not very optimistic about our odds.",
    "There were a lot of explosions for two people blending in.",
    "Tell me have you seen the marvelous breadfish swimming in the ocean water?",
    "Who doesn't like hats?",
    "They don't give PhDs to the smartest people. They give them to the most stubborn.",
    "There seems to be no sign of intelligent life anywhere.",
    "It's a fusion of jazz and funk. It's called 'junk'!",
    "What's the difference between a tube and a foolish Dutchman? One's a hollow cylinder, and the other a silly Hollander.",
    "G is for war crimes",
    "R is for heinous",
    "Would you be willing to drive me to papa John's if I gave you a slice of pizza?",
    "Expectations are premediated resentments",
    "A slice of applie pie is $2.50 in Jamaica and $3.00 in the Bahamas. These are the pie rates of the Caribbean.",
    "...why don't we just take the safety labels off of everything and let the problem solve itself?",
    "hunter2",
    "99.9% of people are idiots. Fortunately, I belong to the 1% of intelligent people.",
    "Good morning, that's a nice tnetennba.",
    "My dear, here we must run as fast as we can, just to stay in place. And if you wish to go anywhere you must run twice as fast as that.",
    "Speak only if it improves upon the silence.",
    "Put your oxygen mask on before helping others.",
]

print(random.choice(phrases))
