#! /usr/bin/env python3
import random

phrases=[
    "As the prophecy foretold.",
    "But at what cost?",
    "So let it be written; so let it be done.",
    "So… it has come to this.",
    "That's just what he/she/they would've said.",
    "Is this why fate brought us together?",
    "And thus, I die",
    "…just like in my dream…",
    "Be that as it may, still may it be as it may be",
    "There is no escape from destiny",
    "Wise words by wise men write wise deeds in wise pen.",
    "In this economy?",
    "…and then the wolves came.",
    "Six one way, half a dozen the other.",
    "Fear not! -- ScoOoOoter",
    "Has anyone really been far even as decided to use even go want to do more like?",
    "I've been further even more decided to use even go need to do look as anyone can!",
    "My best idea was walking to the edge of the earth but no one would go with me.",
    "has-anyone-really-been-far-as it goes I do-look-more-like.",
    "I have no strong feelings one way or the other.",
    "I think there's a \"k\" in knucklehead.",
    "I have 4 other goals to accomplish today.",
    "…in the noon. -- ScoOoOoter",
    "I punch those numbers into my calculator, it makes a happy face!",
    "It\'s my first day!",
    "Send in the clergy! They can move diagonally!",
    "Rest assured that all lethal military androids have been provided with one copy of the Laws of Robotics. To share.",
    "To shreds you say?",
    "Super easy! Barely an inconvenience!",
    "All hail Hypnotoad!",
    "Hold on, let me grab my cheese funnel.",
    "Bob Vance - Vance refridgeration",
    "And that\'s the way the cookie crumbles",
    "At no point in your rambling, incoherent response were you even close to anything that could be considered a rational thought",
    "I award you no points and may God have mercy on your soul",
    "It\'s Halloween.... That\'s really good timing!",
    "Ok, lamp time\'s over!",
    "This isn\'t Sesame Street...",
    "Exit only!",
    "My plan is to forget the whole thing and hope for the best.",
    "Please stop screaming into the void. It's getting full.",
    "Today is brought to you by the letters \"W\", \"T\", and \"F\"",
    "That sentence ended a lot better than it began!",
    "Now with even less asbestos!",
    "Not everyone who wears a sweater is Mr. Rogers.",
    "He doesn\'t know how to use the 3 seashells!",
    "Am I sgeaking a different language?!?",
    "You can\'t steer with a rudder like that!",
    "Whatever boats your float!",
    "Boaty McBoatface",
    "Never underestimate the cleverness of fools",
    "On today's episode of \'Why is this sticky?\'..."
]


print(random.choice(phrases))
