#! /usr/bin/env python3
import random

phrases=[
    "As the prophecy foretold.",
    "But at what cost?",
    "So let it be written; so let it be done.",
    "So… it has come to this.",
    "That\'s just what he/she/they would\'ve said.",
    "Is this why fate brought us together?",
    "And thus, I die",
    "…just like in my dream…",
    "Be that as it may, still may it be as it may be",
    "There is no escape from destiny",
    "Wise words by wise men write wise deeds in wise pen.",
    "In this economy?",
    "…and then the wolves came.",
    "Six one way, half a dozen the other.",
    "Fear not! -- ScoOoOoter",
    "Has anyone really been far even as decided to use even go want to do more like?",
    "I\'ve been further even more decided to use even go need to do look as anyone can!",
    "My best idea was walking to the edge of the earth but no one would go with me.",
    "has-anyone-really-been-far-as it goes I do-look-more-like.",
    "I have no strong feelings one way or the other.",
    "I think there\'s a \"k\" in knucklehead.",
    "I have 4 other goals to accomplish today.",
    "…in the noon. -- ScoOoOoter",
    "I punch those numbers into my calculator, it makes a happy face!",
    "It\'s my first day!",
    "Send in the clergy! They can move diagonally!",
    "Rest assured that all lethal military androids have been provided with one copy of the Laws of Robotics. To share.",
    "To shreds you say?",
    "Super easy! Barely an inconvenience!",
    "All hail Hypnotoad!",
    # "Hold on, let me grab my cheese funnel.",
    "Bob Vance - Vance refrigeration",
    "And that\'s the way the cookie crumbles",
    "At no point in your rambling, incoherent response were you even close to anything that could be considered a rational thought",
    "I award you no points and may God have mercy on your soul",
    "It\'s Halloween.... That\'s really good timing!",
    "Ok, lamp time\'s over!",
    "This isn\'t Sesame Street...",
    # "Exit only!",
    "My plan is to forget the whole thing and hope for the best.",
    "Please stop screaming into the void. It\'s getting full.",
    "Today is brought to you by the letters \"W\", \"T\", and \"F\"",
    "That sentence ended a lot better than it began",
    "Now with even less asbestos!",
    "Not everyone who wears a sweater is Mr. Rogers.",
    "He doesn\'t know how to use the 3 seashells!",
    "Am I sgeaking a different language?!?",
    "You can\'t steer with a rudder like that",
    "Whatever boats your float",
    "Boaty McBoatface",
    "Never underestimate the cleverness of fools",
    "On today\'s episode of \'Why is this sticky?\'...",
    "A lack of planning on your part does not constitute an emergency on mine.",
    "Technically correct... the best kind of correct",
    "0118 999 881 999 119 7253",
    "Quando omni flunks moritati",
    "The early bird gets the worm, but the second rat gets the cheese.",
    "That happens sometimes",
    "...and my middle name is Kurt, not Fart",
    "Never do this to a badger...",
    "KWYJIBO",
    "You\'re paying way too much for worms, man. Who's your worm guy?",
    "I\'m the reason we have rules.",
    "If I can\'t scuba, then what\'s this all been about?",
    "The Enrichment Center reminds you that the Weighted Companion Cube cannot speak.",
    "Well done. Here come the test results: You are a horrible person.",
    "I\'m serious, that\'s what it says: A horrible person. We weren\'t even testing for that.",
    "How the turns have tabled...",
    "So do both of yourselves a favor and just let that handsome devil go about his business.",
    "...that's not part of the test. That\'s asbestos.",
    "You\'re not a super cop are you? You\'re just an ordinary idiot.",
    "But for the love of God Patrick, you\'re not a sheep dog!",
    "Do you know how expensive that cheese was? We might as well had built a children\'s hospital!",
    "In this house we obey the laws of thermodynamics!",
    "Why do I get the feeling that someday I\'ll be describing this to a psychiatrist?",
    "Anyway, don\'t stress yourself thinking about it. Visualizing the scenario while under stress actually triggers the reaction.",
    "Go to the Winchester, have a nice cold pint, and wait for all of this to blow over.",
    "Freaking Canada",
    "I found it on the hair dryer!",
    "Me fail English? That\'s unpossible!",
    "Stupid sexy Flanders",
    "Uh....Are you gonna tell her?",
    "Kerfonta University: Home of the Schooler",
    "We do what we must because we can",
    "Luck is a concept invented by the weak to explain their failures.",
    "Apathy's a tragedy and boredom is a crime.",
    "I eat all of the cheese",
    "My mush is brian",
    "I can\'t believe you\'ve done this",
    "I like the on that insults me sometimes better"
]


print(random.choice(phrases))
